// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class Company
    {
        public Company()
        {
            Vendors = new HashSet<Vendor>();
        }

        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public int? CratedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}